enabled: true
dropdown:
  enabled: true
footer_credit: true
copyright:
  year: '2019'
  name: 'Jason Cox'
  link: 'https://jasoncarloscox.com'
custom_logo:
  user/images/webfolio/logo.png:
    name: logo.png
    type: image/png
    size: 35720
    path: user/images/webfolio/logo.png
custom_logo_mobile:
  user/images/webfolio/logo-mobile.png:
    name: logo-mobile.png
    type: image/png
    size: 33462
    path: user/images/webfolio/logo-mobile.png
favicon:
  user/images/webfolio/favicon.png:
    name: favicon.png
    type: image/png
    size: 4682
    path: user/images/webfolio/favicon.png
